Rebase to Master
magestat/magento2-facebook-pixel pull request #20
Opened 2021-12-15 13:54 UTC by williankeller

2021-12-15 14:53 UTC, erfanimani requested changes

2021-12-15 14:53 UTC, erfanimani commented on etc/csp_whitelist.xml
> +<?xml version="1.0"?>
Using tabs instead of spaces

2021-12-16 00:51 UTC, erfanimani approved these changes

2021-12-16 11:40 UTC, viniciusfabri approved these changes

2021-12-16 11:40 UTC, merged